<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AuditPopup_RE_Subtenant.aspx.cs" Inherits="SONIC_RealEstate_AuditPopup_RE_Information" %><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head runat="server">    <title>eRIMS Sonic :: RE_Subtenant Audit Trail</title></head><script language="javascript" type="text/javascript">    function showAudit(divHeader,divGrid)    {                var divheight,i;               divHeader.style.width = window.screen.availWidth - 225 + "px";        divGrid.style.width = window.screen.availWidth - 225 + "px";                divheight = divGrid.style.height;                i = divheight.indexOf('px');                        if(i > -1)                    divheight = divheight.substring(0,i);        if (divheight > (window.screen.availHeight - 350) && divGrid.style.height != "")        {                        divGrid.style.height = window.screen.availHeight - 350;        }    }        function ChangeScrollBar(f,s)    {        s.scrollTop = f.scrollTop;        s.scrollLeft = f.scrollLeft;    }</script><body>    <form id="form1" runat="server">    <table width="100%" align="left">        <tr>            <td align="left">                <asp:Label ID="lbltable_Name" runat="server" Font-Bold="true"></asp:Label>            </td>            <td align="right">                <a href="javascript:window.close();">Close Window</a>            </td>        </tr>        <tr>            <td colspan="2">                <div style="overflow: hidden; width: 650px;" id="dvHeader" runat="server">                    <table cellpadding="4" cellspacing="0" style="width: 600px; border-collapse: collapse;">                        <tbody>                            <tr style="background-color: #95B3D7; color: White; font-size: 12px; font-weight: bold;"                                align="left">                                <th class="cols">                                    <span style="display: inline-block; width: 100px;">Audit_DateTime</span>                                </th>                                                                <th class="cols">	                                <span style="display: inline-block;width:150px;">PK_RE_Subtenant</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:150px;">FK_RE_Information</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:170px;">Subtenant/DBA</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:250px;">Subtenant Mailing Address 1</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:250px;">Subtenant Mailing Address 2</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:150px;">Subtenant Mailing City</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:200px;">Subtenant Mailing State</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:210px;">Subtenant Mailing Zip Code</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:150px;">Subtenant Telephone</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:200px;">Cancel Options</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:200px;">Renew Options</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:200px;">Option Notification</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:200px;">Notification Due Date</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:150px;">Subtenant Base Rent</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:200px;">Subtenant Monthly Rent</span>                                </th>
                                 <th class="cols">	                                <span style="display: inline-block;width:200px;">Security Deposit </span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:200px;">Escalation</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:150px;">Percentage Rate</span>                                </th>
                                <th class="cols">	                                <span style="display: inline-block;width:130px;">Increase</span>                                </th>                                <th class="cols">                                    <span style="display: inline-block; width: 110px;">Updated_By</span>                                </th>                                <th class="cols">                                    <span style="display: inline-block; width: 117px;">Updated_Date</span>                                </th>                            </tr>                        </tbody>                    </table>                </div>                <div style="overflow: scroll; width: 600px; height: 425px;" id="dvGrid" runat="server">                    <asp:GridView ID="gvRE_Subtenant" runat="server" AutoGenerateColumns="False" CellPadding="4"                        EnableTheming="True" EmptyDataText="No records found!" ShowHeader="false">                        <RowStyle HorizontalAlign="Left" VerticalAlign="Top" />                        <Columns>                            <asp:TemplateField HeaderText="Audit_DateTime">                                <ItemStyle CssClass="cols" Width="100px" />                                <ItemTemplate>                                    <asp:Label ID="lblAudit_DateTime" runat="server" Text='<%# Convert.ToDateTime(Eval("Audit_DateTime")).ToString("yyyy-MM-dd HH:mm")%>'                                            ToolTip='<%# Convert.ToDateTime(Eval("Audit_DateTime")).ToString("yyyy-MM-dd HH:mm")%>'                                            Width="100px"></asp:Label>                                </ItemTemplate>                            </asp:TemplateField>                            <asp:TemplateField HeaderText="PK_RE_Subtenant" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblPK_RE_Subtenant" runat="server" Text='<%#Eval("PK_RE_Subtenant")%>' Width="150px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="FK_RE_Information" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblFK_RE_Information" runat="server" Text='<%#Eval("FK_RE_Information")%>' Width="150px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Subtenant_DBA" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblSubtenant_DBA" runat="server" Text='<%#Eval("Subtenant_DBA")%>' Width="170px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Subtenant_Mailing_Address1" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblSubtenant_Mailing_Address1" runat="server" Text='<%#Eval("Subtenant_Mailing_Address1")%>' Width="250px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Subtenant_Mailing_Address2" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblSubtenant_Mailing_Address2" runat="server" Text='<%#Eval("Subtenant_Mailing_Address2")%>' Width="250px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Subtenant_Mailing_City" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblSubtenant_Mailing_City" runat="server" Text='<%#Eval("Subtenant_Mailing_City")%>' Width="150px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="PK_Subtenant_Mailing_State" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblPK_Subtenant_Mailing_State" runat="server" Text='<%#Eval("PK_Subtenant_Mailing_State")%>' Width="200px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Subtenant_Mailing_Zip_Code" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblSubtenant_Mailing_Zip_Code" runat="server" Text='<%#Eval("Subtenant_Mailing_Zip_Code")%>' Width="210px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Subtenant_Telephone" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblSubtenant_Telephone" runat="server" Text='<%#Eval("Subtenant_Telephone")%>' Width="150px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Cancel_Options" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblCancel_Options" runat="server" Text='<%#Eval("Cancel_Options")%>' Width="200px" CssClass="TextClip"></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Renew_Options" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblRenew_Options" runat="server" Text='<%#Eval("Renew_Options")%>' Width="200px" CssClass="TextClip"></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Option_Notification" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblOption_Notification" runat="server" Text='<%#Eval("Option_Notification")%>' Width="200px" CssClass="TextClip"></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Notification_Due_Date" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblNotification_Due_Date" runat="server" Text='<%#Eval("Notification_Due_Date") != DBNull.Value ? clsGeneral.FormatDateToDisplay(Convert.ToDateTime(Eval("Notification_Due_Date"))) : ""%>' Width="200px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Subtenant_Base_Rent" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblSubtenant_Base_Rent" runat="server" Text='<%#clsGeneral.GetStringValue(Eval("Subtenant_Base_Rent"))%>' Width="150px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Subtenant_Monthly_Rent" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblSubtenant_Monthly_Rent" runat="server" Text='<%#clsGeneral.GetStringValue(Eval("Subtenant_Monthly_Rent"))%>' Width="200px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                              <asp:TemplateField HeaderText="Security_Deposit" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblSecurity_Deposit" runat="server" Text='<%#clsGeneral.GetStringValue(Eval("Security_Deposit"))%>' Width="200px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="FK_LU_Escalation" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblFK_LU_Escalation" runat="server" Text='<%#Eval("FK_LU_Escalation")%>' Width="200px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Percentage_Rate" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblPercentage_Rate" runat="server" Text='<%#Eval("Percentage_Rate")%>' Width="150px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Increase" >	                            <ItemStyle CssClass="cols" />	                            <ItemTemplate>		                            <asp:Label ID="lblIncrease" runat="server" Text='<%#clsGeneral.GetStringValue(Eval("Increase"))%>' Width="130px" ></asp:Label>	                            </ItemTemplate>                            </asp:TemplateField>                            <asp:TemplateField HeaderText="Updated_By">                                <ItemStyle CssClass="cols" Width="110px" />                                <ItemTemplate>                                    <asp:Label ID="lblUpdated_By" runat="server" Text='<%#Eval("user_Name")%>' Width="110px"></asp:Label>                                </ItemTemplate>                            </asp:TemplateField>                            <asp:TemplateField HeaderText="Updated_Date">                                <ItemStyle CssClass="cols" Width="100px" />                                <ItemTemplate>                                    <asp:Label ID="lblUpdated_Date" runat="server" Text='<%#Eval("Update_Date") != DBNull.Value ? clsGeneral.FormatDateToDisplay(Convert.ToDateTime(Eval("Update_Date"))) : ""%>'                                        Width="100px"></asp:Label>                                </ItemTemplate>                            </asp:TemplateField>                        </Columns>                    </asp:GridView>                </div>            </td>        </tr>    </table>    </form></body></html>